"""schema inicial

Revision ID: b631ee491244
Revises: 
Create Date: 2026-09-12 21:51:19.677060
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_schema_inicial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_parameters',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=96), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('is_community_sourced', sa.Boolean(), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('item_categories',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.SmallInteger(), nullable=True),
    sa.Column('display_name', sa.String(length=96), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code <> ''", name='ck_item_categories_code_not_empty'),
    sa.ForeignKeyConstraint(['parent_id'], ['item_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('locations',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('aodp_name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('supports_buy_orders', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('royal_city', 'black_market', 'portal_city', 'rest_zone', 'other')", name='ck_locations_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aodp_name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('servers',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('aodp_base_url', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('collector_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collector', sa.String(length=64), nullable=False),
    sa.Column('server_id', sa.SmallInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('http_requests', sa.Integer(), nullable=False),
    sa.Column('rows_upserted', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('rate_limited_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'success', 'partial', 'failed')", name='ck_collector_runs_status'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collector_runs_recent', 'collector_runs', ['collector', 'started_at'], unique=False)
    op.create_table('gold_prices',
    sa.Column('server_id', sa.SmallInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('price > 0', name='ck_gold_prices_price'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('server_id', 'ts')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unique_name', sa.String(length=128), nullable=False),
    sa.Column('base_name', sa.String(length=128), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=True),
    sa.Column('enchantment', sa.SmallInteger(), nullable=False),
    sa.Column('category_id', sa.SmallInteger(), nullable=True),
    sa.Column('subcategory_code', sa.String(length=64), nullable=True),
    sa.Column('display_name_en', sa.String(length=255), nullable=True),
    sa.Column('display_name_pt', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_quality', sa.SmallInteger(), nullable=True),
    sa.Column('is_tracked', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('enchantment BETWEEN 0 AND 4', name='ck_items_enchantment'),
    sa.CheckConstraint('max_quality IS NULL OR max_quality BETWEEN 1 AND 5', name='ck_items_max_quality'),
    sa.CheckConstraint('tier IS NULL OR tier BETWEEN 1 AND 8', name='ck_items_tier'),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_name')
    )
    op.create_index('ix_items_base_name', 'items', ['base_name'], unique=False)
    op.create_index('ix_items_category', 'items', ['category_id'], unique=False)
    op.create_index('ix_items_tier_enchantment', 'items', ['tier', 'enchantment'], unique=False)
    op.create_table('raw_responses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.Column('server_id', sa.SmallInteger(), nullable=True),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('request_url', sa.Text(), nullable=False),
    sa.Column('http_status', sa.SmallInteger(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_responses_fetched', 'raw_responses', ['fetched_at'], unique=False)
    op.create_table('market_history',
    sa.Column('server_id', sa.SmallInteger(), nullable=False),
    sa.Column('location_id', sa.SmallInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.SmallInteger(), nullable=False),
    sa.Column('timescale', sa.SmallInteger(), nullable=False),
    sa.Column('bucket_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.BigInteger(), nullable=False),
    sa.Column('is_outlier', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('item_count >= 0', name='ck_market_history_item_count'),
    sa.CheckConstraint('quality BETWEEN 1 AND 5', name='ck_market_history_quality'),
    sa.CheckConstraint('timescale IN (1, 6, 24)', name='ck_market_history_timescale'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('server_id', 'location_id', 'item_id', 'quality', 'timescale', 'bucket_ts')
    )
    op.create_index('ix_market_history_lookup', 'market_history', ['server_id', 'item_id', 'timescale', 'bucket_ts'], unique=False)
    op.create_table('market_prices',
    sa.Column('server_id', sa.SmallInteger(), nullable=False),
    sa.Column('location_id', sa.SmallInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.SmallInteger(), nullable=False),
    sa.Column('sell_price_min', sa.BigInteger(), nullable=True),
    sa.Column('sell_price_min_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sell_price_max', sa.BigInteger(), nullable=True),
    sa.Column('sell_price_max_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buy_price_min', sa.BigInteger(), nullable=True),
    sa.Column('buy_price_min_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buy_price_max', sa.BigInteger(), nullable=True),
    sa.Column('buy_price_max_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('(sell_price_min IS NULL OR sell_price_min > 0) AND (sell_price_max IS NULL OR sell_price_max > 0) AND (buy_price_min IS NULL OR buy_price_min > 0) AND (buy_price_max IS NULL OR buy_price_max > 0)', name='ck_market_prices_no_zero_sentinel'),
    sa.CheckConstraint('quality BETWEEN 1 AND 5', name='ck_market_prices_quality'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('server_id', 'location_id', 'item_id', 'quality')
    )
    op.create_index('ix_market_prices_observed', 'market_prices', ['server_id', 'observed_at'], unique=False)
    op.create_index('ix_market_prices_server_item', 'market_prices', ['server_id', 'item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_prices_server_item', table_name='market_prices')
    op.drop_index('ix_market_prices_observed', table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index('ix_market_history_lookup', table_name='market_history')
    op.drop_table('market_history')
    op.drop_index('ix_raw_responses_fetched', table_name='raw_responses')
    op.drop_table('raw_responses')
    op.drop_index('ix_items_tier_enchantment', table_name='items')
    op.drop_index('ix_items_category', table_name='items')
    op.drop_index('ix_items_base_name', table_name='items')
    op.drop_table('items')
    op.drop_table('gold_prices')
    op.drop_index('ix_collector_runs_recent', table_name='collector_runs')
    op.drop_table('collector_runs')
    op.drop_table('servers')
    op.drop_table('locations')
    op.drop_table('item_categories')
    op.drop_table('data_sources')
    op.drop_table('config_parameters')
    # ### end Alembic commands ###
