"""receitas de crafting

Revision ID: bde934a814f6
Revises: 0002_seed_referencia
Create Date: 2026-09-12 23:55:21.489494
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0003_receitas'
down_revision: str | None = '0002_seed_referencia'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Removidos os alter_column que o autogenerate propôs em servers.id,
    # locations.id, item_categories.id e data_sources.id: ele confunde
    # SmallInteger PK com o SERIAL que o Postgres criou. Reescrever chave
    # primária referenciada por FK é risco gratuito numa migration que só
    # precisa criar duas tabelas.
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('output_item_id', sa.Integer(), nullable=False),
    sa.Column('variant_index', sa.SmallInteger(), nullable=False),
    sa.Column('output_quantity', sa.Integer(), nullable=False),
    sa.Column('focus_cost', sa.Integer(), nullable=False),
    sa.Column('silver_cost', sa.Integer(), nullable=False),
    sa.Column('craft_time', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('station_category', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('focus_cost >= 0', name='ck_recipes_focus_cost'),
    sa.CheckConstraint('output_quantity > 0', name='ck_recipes_output_quantity'),
    sa.ForeignKeyConstraint(['output_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipes_output', 'recipes', ['output_item_id'], unique=False)
    op.create_index('uq_recipes_variant', 'recipes', ['output_item_id', 'variant_index'], unique=True)
    op.create_table('recipe_materials',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_returnable', sa.Boolean(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_recipe_materials_quantity'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'item_id')
    )
    op.create_index('ix_recipe_materials_item', 'recipe_materials', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_materials_item', table_name='recipe_materials')
    op.drop_table('recipe_materials')
    op.drop_index('uq_recipes_variant', table_name='recipes')
    op.drop_index('ix_recipes_output', table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
